# Generated by Django 2.2.16 on 2021-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'админ'), ('user', 'юзер'), ('moderator', 'модератор')], default='user', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
