# Generated by Django 2.2.16 on 2021-08-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'юзер'), ('admin', 'админ'), ('moderator', 'модератор')], default='user', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
