# Generated by Django 2.2.16 on 2021-08-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20210810_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'админ'), ('moderator', 'модератор'), ('user', 'юзер')], default='user', max_length=50, verbose_name='Роль пользователя'),
        ),
    ]
